spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/logistics_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rohan
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a7516-4d10-4bd4-bd97-3be18d52c7dc
jwt.expiration=86400000
